// Generated by https://quicktype.io

export interface IAwsResponse {
  Name: string;
  Confidence: number;
  Instances: IInstance[];
}

export interface IInstance {
  BoundingBox: IBoundingBox;
  Confidence: number;
}

export interface IBoundingBox {
  Width: number;
  Height: number;
  Left: number;
  Top: number;
}
// Generated by https://quicktype.io

export interface PersonRenaper {
  code: number;
  message: string;
  person: Person;
  valid: string;
}

export interface Person {
  number: string;
  gender: string;
  names: string;
  lastNames: string;
  birthdate: string;
  copy: string;
  expirationDate: string;
  creationDate: string;
  cuil: string;
  streetAddress: string;
  numberStreet: string;
  floor: string;
  department: string;
  zipCode: string;
  city: string;
  municipality: string;
  province: string;
  country: string;
  messageOfDeath: string;
  nationality: string;
  countryBirth: string;
}
